language: ruby
rvm:
  - "2.1.5"
addons:
  postgresql: "9.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create database "calfresh-and-so-clean_test";' -U postgres
script:
  - "xvfb-run -a bundle exec rspec spec"
